version: '3.8'

services:
  postgres-server:
    image: postgres:16
    container_name: postgres-server
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      #- ./initdb:/docker-entrypoint-initdb.d  # Scripts SQL de inicio opcionales
    networks:
      - postgres-net

volumes:
  postgres-data:

networks:
  postgres-net:
    driver: bridge
    